language: node_js
sudo: false
node_js:
- '10'
os:
- linux
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
  - os: linux
    env: CXX=clang++
branches:
  only:
  - master
  - "/^v.*$/"
deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: false
    tags: true
