language: node_js
sudo: false
node_js:
- '10'
os:
- linux
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
  - os: linux
    env: CXX=clang++
branches:
  only:
  - master
  - "/^v.*$/"
deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -- -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: false
    tags: true
env:
  global:
    secure: iZN5wk8Tb82MYA/vYnPZRPdiBiKZHo+6DadDkxtphuNmA1W3Ml4q8jVud1YUE4kd08fvrHYHmedUZ6wmOiF+U9RI9kShHPe/7ZPwflN3/FAtnkxhc0GRQH816GY2qvBpreI/n6S6dKpP/yLnVi13bv5BLjcVBa5B0F/vf0eCM4IG3mKG8VK3oQCgYE/iZTMYO8zA0vEB74IGLhxzOo5q7uplKsoNl3lelUyTpYDfHltNpYITtXDslComhtTn6tdqEBDiXIE5tySuC1Kd82sO2+tT7i7UQKomo69HFTQM7By1rLgo05z7UqAo1mWCiGOqwFWFcpU/y1CJrqzSaTm54Z/RT6fLcIA8PTlT+UZf8GNvoFJ0duO+Dt5pxK1wzd1ixhBTG9a7gu3TKg5p3lFXSs282wNt3NannObjNoAJ9+eKxEZ8AHbMKiOAv66WE8hvTfSgA1aLmhMfOpAhXV/MB11omDzGiVEKC9bgF2KoTrJD/loyyYkHRn5XlHKqsxk56S2fk4A57HEd+90EABWq8IQbj2TDVT2OKbYVWvusc9HXfpATcXiArnbn1Az6Kw782tb8UgV/JbJkftlUji+HQDZKwPYvltQJ4H37fnEr5tH67nWjIPk/N6ia40mjlBlgd+UMwUl5wwRP5BrOXPpEpBr7FMK0lfzCAP46G3TrAX4=
