image: Visual Studio 2015

environment:
  NODEJS_VERSION: "10"
  PREBUILD_UPLOAD:
    secure: 0M8e0ymFVhGFGTJQ+yHvEF7PK09mS2v2L3zfCW7OztoRmsCW7NlUx7tyDbtpy5/n

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run test-windows

build: off

branches:
  only:
    - master
    - /^v.*$/

deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)
